<<<<<<< HEAD
[2018-10-13 22:57:33,242] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-13 22:58:04,643] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-14 17:19:50,513] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-14 17:28:38,097] [INFO] "GET /api/jingdianlist/1 HTTP/1.1" 200 3883
[2018-10-14 17:33:11,584] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 72
[2018-10-14 17:33:54,285] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 76
[2018-10-14 17:33:59,910] [INFO] "GET /api/jingqucount/2 HTTP/1.1" 200 77
[2018-10-14 17:34:21,414] [INFO] "GET /api/jingqucount/18 HTTP/1.1" 200 75
[2018-10-14 17:34:29,214] [INFO] "GET /api/jingqucount/17 HTTP/1.1" 200 76
[2018-10-14 17:34:35,536] [INFO] "GET /api/jingqucount/11 HTTP/1.1" 200 76
[2018-10-14 18:19:55,587] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 19, in get_jingqu_detail
    this_year_comments = comment.objects(data_region__contains = search_key,comment_time__contains = str(datetime.datetime().year));
TypeError: Required argument 'year' (pos 1) not found
[2018-10-14 18:19:56,457] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 96017
[2018-10-14 18:23:19,354] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 44, in get_jingqu_detail
    res['thisMonthCommentNumber'] = this_year_month_comments.average('comment_score').count();
AttributeError: 'float' object has no attribute 'count'
[2018-10-14 18:23:37,456] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 100176
[2018-10-14 18:24:12,886] [INFO] "GET /api/jingqudetail/1 HTTP/1.1" 200 236
[2018-10-14 18:27:43,292] [INFO] "GET /api/jingqudetail/2 HTTP/1.1" 200 237
[2018-10-14 20:17:15,698] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:02,709] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:04,641] [INFO] "OPTIONS /api/getAllTour HTTP/1.1" 200 0
[2018-10-14 20:18:04,705] [WARNING] Not Found: /api/getAllTour
[2018-10-14 20:18:04,710] [WARNING] "POST /api/getAllTour HTTP/1.1" 404 2882
[2018-10-14 20:20:29,291] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:20:43,092] [INFO] "OPTIONS /api/jingqulist HTTP/1.1" 200 0
[2018-10-14 20:20:43,155] [WARNING] "POST /api/jingqulist HTTP/1.1" 405 41
[2018-10-14 20:21:01,434] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:21:23,469] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 13:41:36,653] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\JingquDymanicCommentView.py", line 53, in post
    return get_jingqu_dymanic_comment(request);
TypeError: get_jingqu_dymanic_comment() missing 1 required positional argument: 'id'
[2018-10-15 13:41:37,482] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17230
[2018-10-15 13:42:37,958] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
TypeError: get_spot_num_compard() missing 1 required positional argument: 'id'
[2018-10-15 13:42:38,206] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17207
[2018-10-15 13:43:10,935] [INFO] This is an errormsg
[2018-10-15 13:43:10,961] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:02,763] [INFO] This is an errormsg
[2018-10-15 13:44:02,773] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:42,636] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 61, in query
    fields = _doc_cls._lookup_field(parts)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\base\document.py", line 1009, in _lookup_field
    raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "comment_month"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 36, in get_spot_num_compard
    cnts.append(comments.count());
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\queryset.py", line 133, in count
    return super(QuerySet, self).count(with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 401, in count
    return self._cursor.count(with_limit_and_skip=with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1567, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1613, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 89, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 155, in accept
    return visitor.visit_query(self)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 63, in query
    raise InvalidQueryError(e)
mongoengine.errors.InvalidQueryError: Cannot resolve field "comment_month"
[2018-10-15 13:44:43,090] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 19034
[2018-10-15 14:25:41,191] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 19, in get_spot_num_compard
    search_keys.append('千岛湖');
AttributeError: 'str' object has no attribute 'append'
[2018-10-15 14:25:41,454] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17308
[2018-10-15 14:26:15,742] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = list(request.POST['regions']);
UnboundLocalError: local variable 'list' referenced before assignment
[2018-10-15 14:26:16,258] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17351
[2018-10-15 14:31:24,998] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程'']
          ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:31:25,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17349
[2018-10-15 14:31:43,377] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 196
[2018-10-15 14:33:52,400] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程','去哪儿','大众点评'']
                       ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:33:52,684] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17385
[2018-10-15 14:34:19,093] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 615
[2018-10-15 14:36:04,035] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1515
[2018-10-15 14:40:13,898] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 14:43:30,487] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 15:34:37,103] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 71, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 37, in get_spot_num_compard
    comments = comment.objects(data_website=website, data_region__contains=region, comment_month=time);
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 190, in _get_collection
    db = cls._get_db()
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 179, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\connection.py", line 236, in get_db
    db.authenticate(conn_settings['username'], conn_settings['password'], **auth_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.55.59.187:28117: [WinError 10065] 套接字操作尝试一个无法连接的主机。
[2018-10-15 15:34:37,694] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 18772
[2018-10-15 15:56:45,533] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'function' object has no attribute 'objects'
[2018-10-15 15:56:53,392] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17448
[2018-10-15 15:57:20,348] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 15:57:28,241] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17447
[2018-10-15 16:00:28,158] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = eval((request.POST.getlist('spots'))[0]);
  File "<string>", line 1
    ['西湖‘]
         ^
SyntaxError: EOL while scanning string literal
[2018-10-15 16:00:28,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17392
[2018-10-15 16:00:46,820] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:00:54,644] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:06,097] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:02:14,195] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:58,607] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = rrcomments.objects(data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:03:06,618] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17419
[2018-10-15 16:03:55,722] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 686
[2018-10-15 16:07:37,000] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1676
[2018-10-15 18:00:30,508] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:00:31,625] [WARNING] Not Found: /favicon.ico
[2018-10-15 18:00:31,630] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 18:01:00,580] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:01:44,793] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:03:48,750] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:06:26,226] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:11:40,829] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:15:53,747] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:17:38,423] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:23:46,598] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:13,627] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:37,393] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:12,294] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:35,255] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:45:56,703] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:46:19,883] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:47:20,267] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:48:11,459] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:01:41,412] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:51,461] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:53,189] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:19,624] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:30,699] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:04:12,967] [INFO] This is an errormsg
[2018-10-15 19:04:12,972] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:16:46,555] [INFO] "GET /api/jingqulist HTTP/1.1" 200 59086
[2018-10-15 19:17:45,017] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:19:34,213] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 19:27:18,648] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3220
[2018-10-15 19:33:02,725] [INFO] This is an errormsg
[2018-10-15 19:33:02,728] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:34:35,422] [INFO] This is an errormsg
[2018-10-15 19:34:35,428] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:36:06,860] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:39,435] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:41,572] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:53,784] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:54,890] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:55,720] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:56,490] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:50:15,882] [INFO] This is an errormsg
[2018-10-15 19:50:15,884] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:58:30,914] [INFO] This is an errormsg
[2018-10-15 19:58:30,917] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:00:38,177] [INFO] This is an errormsg
[2018-10-15 20:00:38,179] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:03:33,637] [INFO] This is an errormsg
[2018-10-15 20:03:33,641] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:04:35,355] [INFO] This is an errormsg
[2018-10-15 20:04:35,360] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:06:15,952] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 20:11:32,361] [INFO] This is an errormsg
[2018-10-15 20:11:32,364] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:14:55,790] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 20:19:00,455] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:21:40,770] [INFO] This is an errormsg
[2018-10-15 20:21:40,795] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:22:55,563] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:15,109] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:31,065] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
=======
[2018-10-13 22:57:33,242] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-13 22:58:04,643] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-14 17:19:50,513] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-14 17:28:38,097] [INFO] "GET /api/jingdianlist/1 HTTP/1.1" 200 3883
[2018-10-14 17:33:11,584] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 72
[2018-10-14 17:33:54,285] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 76
[2018-10-14 17:33:59,910] [INFO] "GET /api/jingqucount/2 HTTP/1.1" 200 77
[2018-10-14 17:34:21,414] [INFO] "GET /api/jingqucount/18 HTTP/1.1" 200 75
[2018-10-14 17:34:29,214] [INFO] "GET /api/jingqucount/17 HTTP/1.1" 200 76
[2018-10-14 17:34:35,536] [INFO] "GET /api/jingqucount/11 HTTP/1.1" 200 76
[2018-10-14 18:19:55,587] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 19, in get_jingqu_detail
    this_year_comments = comment.objects(data_region__contains = search_key,comment_time__contains = str(datetime.datetime().year));
TypeError: Required argument 'year' (pos 1) not found
[2018-10-14 18:19:56,457] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 96017
[2018-10-14 18:23:19,354] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 44, in get_jingqu_detail
    res['thisMonthCommentNumber'] = this_year_month_comments.average('comment_score').count();
AttributeError: 'float' object has no attribute 'count'
[2018-10-14 18:23:37,456] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 100176
[2018-10-14 18:24:12,886] [INFO] "GET /api/jingqudetail/1 HTTP/1.1" 200 236
[2018-10-14 18:27:43,292] [INFO] "GET /api/jingqudetail/2 HTTP/1.1" 200 237
[2018-10-14 20:17:15,698] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:02,709] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:04,641] [INFO] "OPTIONS /api/getAllTour HTTP/1.1" 200 0
[2018-10-14 20:18:04,705] [WARNING] Not Found: /api/getAllTour
[2018-10-14 20:18:04,710] [WARNING] "POST /api/getAllTour HTTP/1.1" 404 2882
[2018-10-14 20:20:29,291] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:20:43,092] [INFO] "OPTIONS /api/jingqulist HTTP/1.1" 200 0
[2018-10-14 20:20:43,155] [WARNING] "POST /api/jingqulist HTTP/1.1" 405 41
[2018-10-14 20:21:01,434] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:21:23,469] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 13:41:36,653] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\JingquDymanicCommentView.py", line 53, in post
    return get_jingqu_dymanic_comment(request);
TypeError: get_jingqu_dymanic_comment() missing 1 required positional argument: 'id'
[2018-10-15 13:41:37,482] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17230
[2018-10-15 13:42:37,958] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
TypeError: get_spot_num_compard() missing 1 required positional argument: 'id'
[2018-10-15 13:42:38,206] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17207
[2018-10-15 13:43:10,935] [INFO] This is an errormsg
[2018-10-15 13:43:10,961] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:02,763] [INFO] This is an errormsg
[2018-10-15 13:44:02,773] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:42,636] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 61, in query
    fields = _doc_cls._lookup_field(parts)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\base\document.py", line 1009, in _lookup_field
    raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "comment_month"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 36, in get_spot_num_compard
    cnts.append(comments.count());
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\queryset.py", line 133, in count
    return super(QuerySet, self).count(with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 401, in count
    return self._cursor.count(with_limit_and_skip=with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1567, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1613, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 89, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 155, in accept
    return visitor.visit_query(self)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 63, in query
    raise InvalidQueryError(e)
mongoengine.errors.InvalidQueryError: Cannot resolve field "comment_month"
[2018-10-15 13:44:43,090] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 19034
[2018-10-15 14:25:41,191] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 19, in get_spot_num_compard
    search_keys.append('千岛湖');
AttributeError: 'str' object has no attribute 'append'
[2018-10-15 14:25:41,454] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17308
[2018-10-15 14:26:15,742] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = list(request.POST['regions']);
UnboundLocalError: local variable 'list' referenced before assignment
[2018-10-15 14:26:16,258] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17351
[2018-10-15 14:31:24,998] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程'']
          ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:31:25,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17349
[2018-10-15 14:31:43,377] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 196
[2018-10-15 14:33:52,400] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程','去哪儿','大众点评'']
                       ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:33:52,684] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17385
[2018-10-15 14:34:19,093] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 615
[2018-10-15 14:36:04,035] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1515
[2018-10-15 14:40:13,898] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 14:43:30,487] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 15:34:37,103] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 71, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 37, in get_spot_num_compard
    comments = comment.objects(data_website=website, data_region__contains=region, comment_month=time);
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 190, in _get_collection
    db = cls._get_db()
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 179, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\connection.py", line 236, in get_db
    db.authenticate(conn_settings['username'], conn_settings['password'], **auth_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.55.59.187:28117: [WinError 10065] 套接字操作尝试一个无法连接的主机。
[2018-10-15 15:34:37,694] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 18772
[2018-10-15 15:56:45,533] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'function' object has no attribute 'objects'
[2018-10-15 15:56:53,392] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17448
[2018-10-15 15:57:20,348] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 15:57:28,241] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17447
[2018-10-15 16:00:28,158] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = eval((request.POST.getlist('spots'))[0]);
  File "<string>", line 1
    ['西湖‘]
         ^
SyntaxError: EOL while scanning string literal
[2018-10-15 16:00:28,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17392
[2018-10-15 16:00:46,820] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:00:54,644] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:06,097] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:02:14,195] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:58,607] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = rrcomments.objects(data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:03:06,618] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17419
[2018-10-15 16:03:55,722] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 686
[2018-10-15 16:07:37,000] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1676
[2018-10-15 18:00:30,508] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:00:31,625] [WARNING] Not Found: /favicon.ico
[2018-10-15 18:00:31,630] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 18:01:00,580] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:01:44,793] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:03:48,750] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:06:26,226] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:11:40,829] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:15:53,747] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:17:38,423] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:23:46,598] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:13,627] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:37,393] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:12,294] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:35,255] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:45:56,703] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:46:19,883] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:47:20,267] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:48:11,459] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:01:41,412] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:51,461] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:53,189] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:19,624] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:30,699] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:04:12,967] [INFO] This is an errormsg
[2018-10-15 19:04:12,972] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:16:46,555] [INFO] "GET /api/jingqulist HTTP/1.1" 200 59086
[2018-10-15 19:17:45,017] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:19:34,213] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 19:27:18,648] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3220
[2018-10-15 19:33:02,725] [INFO] This is an errormsg
[2018-10-15 19:33:02,728] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:34:35,422] [INFO] This is an errormsg
[2018-10-15 19:34:35,428] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:36:06,860] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:39,435] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:41,572] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:53,784] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:54,890] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:55,720] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:56,490] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:50:15,882] [INFO] This is an errormsg
[2018-10-15 19:50:15,884] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:58:30,914] [INFO] This is an errormsg
[2018-10-15 19:58:30,917] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:00:38,177] [INFO] This is an errormsg
[2018-10-15 20:00:38,179] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:03:33,637] [INFO] This is an errormsg
[2018-10-15 20:03:33,641] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:04:35,355] [INFO] This is an errormsg
[2018-10-15 20:04:35,360] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:06:15,952] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 20:11:32,361] [INFO] This is an errormsg
[2018-10-15 20:11:32,364] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:14:55,790] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 20:19:00,455] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:21:40,770] [INFO] This is an errormsg
[2018-10-15 20:21:40,795] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:22:55,563] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:15,109] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:31,065] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 12:39:42,064] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 12:39:42,197] [WARNING] Not Found: /favicon.ico
[2018-10-15 12:39:42,197] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 13:04:44,653] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 13:18:41,721] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 13:24:48,629] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 14:58:01,271] [INFO] This is an errormsg
[2018-10-15 14:58:01,289] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 14:58:01,367] [WARNING] Not Found: /favicon.ico
[2018-10-15 14:58:01,368] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 14:59:50,915] [INFO] This is an errormsg
[2018-10-15 14:59:50,916] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
>>>>>>> 7e6f8e4230555896acacc7a72ae975759fb7d685
