<<<<<<< HEAD
[2018-10-13 22:57:33,242] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-13 22:58:04,643] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-14 17:19:50,513] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-14 17:28:38,097] [INFO] "GET /api/jingdianlist/1 HTTP/1.1" 200 3883
[2018-10-14 17:33:11,584] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 72
[2018-10-14 17:33:54,285] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 76
[2018-10-14 17:33:59,910] [INFO] "GET /api/jingqucount/2 HTTP/1.1" 200 77
[2018-10-14 17:34:21,414] [INFO] "GET /api/jingqucount/18 HTTP/1.1" 200 75
[2018-10-14 17:34:29,214] [INFO] "GET /api/jingqucount/17 HTTP/1.1" 200 76
[2018-10-14 17:34:35,536] [INFO] "GET /api/jingqucount/11 HTTP/1.1" 200 76
[2018-10-14 18:19:55,587] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 19, in get_jingqu_detail
    this_year_comments = comment.objects(data_region__contains = search_key,comment_time__contains = str(datetime.datetime().year));
TypeError: Required argument 'year' (pos 1) not found
[2018-10-14 18:19:56,457] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 96017
[2018-10-14 18:23:19,354] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 44, in get_jingqu_detail
    res['thisMonthCommentNumber'] = this_year_month_comments.average('comment_score').count();
AttributeError: 'float' object has no attribute 'count'
[2018-10-14 18:23:37,456] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 100176
[2018-10-14 18:24:12,886] [INFO] "GET /api/jingqudetail/1 HTTP/1.1" 200 236
[2018-10-14 18:27:43,292] [INFO] "GET /api/jingqudetail/2 HTTP/1.1" 200 237
[2018-10-14 20:17:15,698] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:02,709] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:04,641] [INFO] "OPTIONS /api/getAllTour HTTP/1.1" 200 0
[2018-10-14 20:18:04,705] [WARNING] Not Found: /api/getAllTour
[2018-10-14 20:18:04,710] [WARNING] "POST /api/getAllTour HTTP/1.1" 404 2882
[2018-10-14 20:20:29,291] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:20:43,092] [INFO] "OPTIONS /api/jingqulist HTTP/1.1" 200 0
[2018-10-14 20:20:43,155] [WARNING] "POST /api/jingqulist HTTP/1.1" 405 41
[2018-10-14 20:21:01,434] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:21:23,469] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 13:41:36,653] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\JingquDymanicCommentView.py", line 53, in post
    return get_jingqu_dymanic_comment(request);
TypeError: get_jingqu_dymanic_comment() missing 1 required positional argument: 'id'
[2018-10-15 13:41:37,482] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17230
[2018-10-15 13:42:37,958] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
TypeError: get_spot_num_compard() missing 1 required positional argument: 'id'
[2018-10-15 13:42:38,206] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17207
[2018-10-15 13:43:10,935] [INFO] This is an errormsg
[2018-10-15 13:43:10,961] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:02,763] [INFO] This is an errormsg
[2018-10-15 13:44:02,773] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:42,636] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 61, in query
    fields = _doc_cls._lookup_field(parts)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\base\document.py", line 1009, in _lookup_field
    raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "comment_month"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 36, in get_spot_num_compard
    cnts.append(comments.count());
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\queryset.py", line 133, in count
    return super(QuerySet, self).count(with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 401, in count
    return self._cursor.count(with_limit_and_skip=with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1567, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1613, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 89, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 155, in accept
    return visitor.visit_query(self)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 63, in query
    raise InvalidQueryError(e)
mongoengine.errors.InvalidQueryError: Cannot resolve field "comment_month"
[2018-10-15 13:44:43,090] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 19034
[2018-10-15 14:25:41,191] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 19, in get_spot_num_compard
    search_keys.append('千岛湖');
AttributeError: 'str' object has no attribute 'append'
[2018-10-15 14:25:41,454] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17308
[2018-10-15 14:26:15,742] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = list(request.POST['regions']);
UnboundLocalError: local variable 'list' referenced before assignment
[2018-10-15 14:26:16,258] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17351
[2018-10-15 14:31:24,998] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程'']
          ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:31:25,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17349
[2018-10-15 14:31:43,377] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 196
[2018-10-15 14:33:52,400] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程','去哪儿','大众点评'']
                       ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:33:52,684] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17385
[2018-10-15 14:34:19,093] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 615
[2018-10-15 14:36:04,035] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1515
[2018-10-15 14:40:13,898] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 14:43:30,487] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 15:34:37,103] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 71, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 37, in get_spot_num_compard
    comments = comment.objects(data_website=website, data_region__contains=region, comment_month=time);
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 190, in _get_collection
    db = cls._get_db()
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 179, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\connection.py", line 236, in get_db
    db.authenticate(conn_settings['username'], conn_settings['password'], **auth_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.55.59.187:28117: [WinError 10065] 套接字操作尝试一个无法连接的主机。
[2018-10-15 15:34:37,694] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 18772
[2018-10-15 15:56:45,533] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'function' object has no attribute 'objects'
[2018-10-15 15:56:53,392] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17448
[2018-10-15 15:57:20,348] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 15:57:28,241] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17447
[2018-10-15 16:00:28,158] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = eval((request.POST.getlist('spots'))[0]);
  File "<string>", line 1
    ['西湖‘]
         ^
SyntaxError: EOL while scanning string literal
[2018-10-15 16:00:28,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17392
[2018-10-15 16:00:46,820] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:00:54,644] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:06,097] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:02:14,195] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:58,607] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = rrcomments.objects(data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:03:06,618] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17419
[2018-10-15 16:03:55,722] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 686
[2018-10-15 16:07:37,000] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1676
[2018-10-15 18:00:30,508] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:00:31,625] [WARNING] Not Found: /favicon.ico
[2018-10-15 18:00:31,630] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 18:01:00,580] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:01:44,793] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:03:48,750] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:06:26,226] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:11:40,829] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:15:53,747] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:17:38,423] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:23:46,598] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:13,627] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:37,393] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:12,294] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:35,255] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:45:56,703] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:46:19,883] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:47:20,267] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:48:11,459] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:01:41,412] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:51,461] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:53,189] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:19,624] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:30,699] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:04:12,967] [INFO] This is an errormsg
[2018-10-15 19:04:12,972] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:16:46,555] [INFO] "GET /api/jingqulist HTTP/1.1" 200 59086
[2018-10-15 19:17:45,017] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:19:34,213] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 19:27:18,648] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3220
[2018-10-15 19:33:02,725] [INFO] This is an errormsg
[2018-10-15 19:33:02,728] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:34:35,422] [INFO] This is an errormsg
[2018-10-15 19:34:35,428] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:36:06,860] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:39,435] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:41,572] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:53,784] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:54,890] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:55,720] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:56,490] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:50:15,882] [INFO] This is an errormsg
[2018-10-15 19:50:15,884] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:58:30,914] [INFO] This is an errormsg
[2018-10-15 19:58:30,917] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:00:38,177] [INFO] This is an errormsg
[2018-10-15 20:00:38,179] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:03:33,637] [INFO] This is an errormsg
[2018-10-15 20:03:33,641] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:04:35,355] [INFO] This is an errormsg
[2018-10-15 20:04:35,360] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:06:15,952] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 20:11:32,361] [INFO] This is an errormsg
[2018-10-15 20:11:32,364] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:14:55,790] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 20:19:00,455] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:21:40,770] [INFO] This is an errormsg
[2018-10-15 20:21:40,795] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:22:55,563] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:15,109] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:31,065] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
=======
[2018-10-13 22:57:33,242] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-13 22:58:04,643] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3058
[2018-10-14 17:19:50,513] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-14 17:28:38,097] [INFO] "GET /api/jingdianlist/1 HTTP/1.1" 200 3883
[2018-10-14 17:33:11,584] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 72
[2018-10-14 17:33:54,285] [INFO] "GET /api/jingqucount/1 HTTP/1.1" 200 76
[2018-10-14 17:33:59,910] [INFO] "GET /api/jingqucount/2 HTTP/1.1" 200 77
[2018-10-14 17:34:21,414] [INFO] "GET /api/jingqucount/18 HTTP/1.1" 200 75
[2018-10-14 17:34:29,214] [INFO] "GET /api/jingqucount/17 HTTP/1.1" 200 76
[2018-10-14 17:34:35,536] [INFO] "GET /api/jingqucount/11 HTTP/1.1" 200 76
[2018-10-14 18:19:55,587] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 19, in get_jingqu_detail
    this_year_comments = comment.objects(data_region__contains = search_key,comment_time__contains = str(datetime.datetime().year));
TypeError: Required argument 'year' (pos 1) not found
[2018-10-14 18:19:56,457] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 96017
[2018-10-14 18:23:19,354] [ERROR] Internal Server Error: /api/jingqudetail/1
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 60, in get
    return get_jingqu_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\jingquDetailView.py", line 44, in get_jingqu_detail
    res['thisMonthCommentNumber'] = this_year_month_comments.average('comment_score').count();
AttributeError: 'float' object has no attribute 'count'
[2018-10-14 18:23:37,456] [ERROR] "GET /api/jingqudetail/1 HTTP/1.1" 500 100176
[2018-10-14 18:24:12,886] [INFO] "GET /api/jingqudetail/1 HTTP/1.1" 200 236
[2018-10-14 18:27:43,292] [INFO] "GET /api/jingqudetail/2 HTTP/1.1" 200 237
[2018-10-14 20:17:15,698] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:02,709] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:18:04,641] [INFO] "OPTIONS /api/getAllTour HTTP/1.1" 200 0
[2018-10-14 20:18:04,705] [WARNING] Not Found: /api/getAllTour
[2018-10-14 20:18:04,710] [WARNING] "POST /api/getAllTour HTTP/1.1" 404 2882
[2018-10-14 20:20:29,291] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:20:43,092] [INFO] "OPTIONS /api/jingqulist HTTP/1.1" 200 0
[2018-10-14 20:20:43,155] [WARNING] "POST /api/jingqulist HTTP/1.1" 405 41
[2018-10-14 20:21:01,434] [INFO] "POST /api/login HTTP/1.1" 200 229
[2018-10-14 20:21:23,469] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 13:41:36,653] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\JingquDymanicCommentView.py", line 53, in post
    return get_jingqu_dymanic_comment(request);
TypeError: get_jingqu_dymanic_comment() missing 1 required positional argument: 'id'
[2018-10-15 13:41:37,482] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17230
[2018-10-15 13:42:37,958] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
TypeError: get_spot_num_compard() missing 1 required positional argument: 'id'
[2018-10-15 13:42:38,206] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17207
[2018-10-15 13:43:10,935] [INFO] This is an errormsg
[2018-10-15 13:43:10,961] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:02,763] [INFO] This is an errormsg
[2018-10-15 13:44:02,773] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 52
[2018-10-15 13:44:42,636] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 61, in query
    fields = _doc_cls._lookup_field(parts)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\base\document.py", line 1009, in _lookup_field
    raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "comment_month"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 63, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 36, in get_spot_num_compard
    cnts.append(comments.count());
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\queryset.py", line 133, in count
    return super(QuerySet, self).count(with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 401, in count
    return self._cursor.count(with_limit_and_skip=with_limit_and_skip)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1567, in _cursor
    self._cursor_obj = self._collection.find(self._query,
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\base.py", line 1613, in _query
    self._mongo_query = self._query_obj.to_query(self._document)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 89, in to_query
    query = query.accept(QueryCompilerVisitor(document))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 155, in accept
    return visitor.visit_query(self)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\visitor.py", line 78, in visit_query
    return transform.query(self.document, **query.query)
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\transform.py", line 63, in query
    raise InvalidQueryError(e)
mongoengine.errors.InvalidQueryError: Cannot resolve field "comment_month"
[2018-10-15 13:44:43,090] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 19034
[2018-10-15 14:25:41,191] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 19, in get_spot_num_compard
    search_keys.append('千岛湖');
AttributeError: 'str' object has no attribute 'append'
[2018-10-15 14:25:41,454] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17308
[2018-10-15 14:26:15,742] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = list(request.POST['regions']);
UnboundLocalError: local variable 'list' referenced before assignment
[2018-10-15 14:26:16,258] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17351
[2018-10-15 14:31:24,998] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程'']
          ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:31:25,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17349
[2018-10-15 14:31:43,377] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 196
[2018-10-15 14:33:52,400] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 15, in get_spot_num_compard
    websites = eval((request.POST.getlist('websites'))[0]);
  File "<string>", line 1
    ['携程','去哪儿','大众点评'']
                       ^
SyntaxError: EOL while scanning string literal
[2018-10-15 14:33:52,684] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17385
[2018-10-15 14:34:19,093] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 615
[2018-10-15 14:36:04,035] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1515
[2018-10-15 14:40:13,898] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 14:43:30,487] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1997
[2018-10-15 15:34:37,103] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 71, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 37, in get_spot_num_compard
    comments = comment.objects(data_website=website, data_region__contains=region, comment_month=time);
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\queryset\manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 190, in _get_collection
    db = cls._get_db()
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\document.py", line 179, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "E:\Anaconda\envs\en1\lib\site-packages\mongoengine\connection.py", line 236, in get_db
    db.authenticate(conn_settings['username'], conn_settings['password'], **auth_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "E:\Anaconda\envs\en1\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.55.59.187:28117: [WinError 10065] 套接字操作尝试一个无法连接的主机。
[2018-10-15 15:34:37,694] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 18772
[2018-10-15 15:56:45,533] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'function' object has no attribute 'objects'
[2018-10-15 15:56:53,392] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17448
[2018-10-15 15:57:20,348] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects(data_website=website, data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 15:57:28,241] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17447
[2018-10-15 16:00:28,158] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 12, in get_spot_num_compard
    search_keys = eval((request.POST.getlist('spots'))[0]);
  File "<string>", line 1
    ['西湖‘]
         ^
SyntaxError: EOL while scanning string literal
[2018-10-15 16:00:28,451] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17392
[2018-10-15 16:00:46,820] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 72, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 38, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:00:54,644] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:06,097] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = comments.objects( data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:02:14,195] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17418
[2018-10-15 16:02:58,607] [ERROR] Internal Server Error: /api/spotnumcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 73, in post
    return get_spot_num_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotNumComparedView.py", line 39, in get_spot_num_compard
    rcomments = rrcomments.objects(data_region__contains=region, comment_month=time);
AttributeError: 'QuerySet' object has no attribute 'objects'
[2018-10-15 16:03:06,618] [ERROR] "POST /api/spotnumcompared HTTP/1.1" 500 17419
[2018-10-15 16:03:55,722] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 686
[2018-10-15 16:07:37,000] [INFO] "POST /api/spotnumcompared HTTP/1.1" 200 1676
[2018-10-15 18:00:30,508] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:00:31,625] [WARNING] Not Found: /favicon.ico
[2018-10-15 18:00:31,630] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 18:01:00,580] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:01:44,793] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:03:48,750] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:06:26,226] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:11:40,829] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:15:53,747] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:17:38,423] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:23:46,598] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:13,627] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:28:37,393] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:12,294] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:32:35,255] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:45:56,703] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:46:19,883] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:47:20,267] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 18:48:11,459] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:01:41,412] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:51,461] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:01:53,189] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:19,624] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:02:30,699] [INFO] "GET /api/jingqulist HTTP/1.1" 200 48
[2018-10-15 19:04:12,967] [INFO] This is an errormsg
[2018-10-15 19:04:12,972] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:16:46,555] [INFO] "GET /api/jingqulist HTTP/1.1" 200 59086
[2018-10-15 19:17:45,017] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3324
[2018-10-15 19:19:34,213] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 19:27:18,648] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3220
[2018-10-15 19:33:02,725] [INFO] This is an errormsg
[2018-10-15 19:33:02,728] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:34:35,422] [INFO] This is an errormsg
[2018-10-15 19:34:35,428] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:36:06,860] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:39,435] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:41,572] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:53,784] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:54,890] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:55,720] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:36:56,490] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 19:50:15,882] [INFO] This is an errormsg
[2018-10-15 19:50:15,884] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 19:58:30,914] [INFO] This is an errormsg
[2018-10-15 19:58:30,917] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:00:38,177] [INFO] This is an errormsg
[2018-10-15 20:00:38,179] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:03:33,637] [INFO] This is an errormsg
[2018-10-15 20:03:33,641] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:04:35,355] [INFO] This is an errormsg
[2018-10-15 20:04:35,360] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:06:15,952] [INFO] "GET /api/jingqulist HTTP/1.1" 200 2644
[2018-10-15 20:11:32,361] [INFO] This is an errormsg
[2018-10-15 20:11:32,364] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:14:55,790] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3094
[2018-10-15 20:19:00,455] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:21:40,770] [INFO] This is an errormsg
[2018-10-15 20:21:40,795] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 20:22:55,563] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:15,109] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 20:23:31,065] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 12:39:42,064] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 12:39:42,197] [WARNING] Not Found: /favicon.ico
[2018-10-15 12:39:42,197] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 13:04:44,653] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 13:18:41,721] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 13:24:48,629] [INFO] "GET /api/jingqulist HTTP/1.1" 200 3076
[2018-10-15 14:58:01,271] [INFO] This is an errormsg
[2018-10-15 14:58:01,289] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
[2018-10-15 14:58:01,367] [WARNING] Not Found: /favicon.ico
[2018-10-15 14:58:01,368] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2867
[2018-10-15 14:59:50,915] [INFO] This is an errormsg
[2018-10-15 14:59:50,916] [INFO] "GET /api/jingqulist HTTP/1.1" 200 57
>>>>>>> 7e6f8e4230555896acacc7a72ae975759fb7d685
[2018-10-17 08:41:09,953] [WARNING] "GET /api/spotlist HTTP/1.1" 401 9379
[2018-10-17 08:41:10,494] [INFO] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2018-10-17 08:41:10,644] [INFO] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
[2018-10-17 08:41:10,792] [INFO] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2018-10-17 08:41:10,802] [INFO] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2018-10-17 08:41:10,807] [INFO] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[2018-10-17 08:41:10,934] [INFO] "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
[2018-10-17 08:41:11,105] [INFO] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
[2018-10-17 08:41:11,166] [INFO] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2018-10-17 08:41:11,689] [INFO] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2018-10-17 08:41:11,704] [INFO] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
[2018-10-17 08:41:11,705] [INFO] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
[2018-10-17 08:41:12,732] [WARNING] Not Found: /favicon.ico
[2018-10-17 08:41:12,735] [WARNING] "GET /favicon.ico HTTP/1.1" 404 2912
[2018-10-17 08:41:18,797] [WARNING] "GET /api/spotlist HTTP/1.1" 401 9379
[2018-10-17 08:41:21,699] [WARNING] "GET /api/spotlist?format=json HTTP/1.1" 401 58
[2018-10-17 08:41:23,985] [WARNING] "GET /api/spotlist HTTP/1.1" 401 9379
[2018-10-17 09:32:27,188] [INFO] This is an errormsg
[2018-10-17 09:32:27,193] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 52
[2018-10-17 09:34:06,985] [INFO] This is an errormsg
[2018-10-17 09:34:06,991] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 52
[2018-10-17 09:36:21,341] [INFO] This is an errormsg
[2018-10-17 09:36:21,346] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 52
[2018-10-17 09:38:17,730] [INFO] This is an errormsg
[2018-10-17 09:38:17,735] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 52
[2018-10-17 09:39:42,405] [INFO] This is an errormsg
[2018-10-17 09:39:42,413] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 52
[2018-10-17 09:41:42,517] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 3677
[2018-10-17 09:41:58,568] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 3677
[2018-10-17 09:55:36,739] [INFO] "GET /api/spotlist HTTP/1.1" 200 3193
[2018-10-17 09:55:46,542] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 3677
[2018-10-17 10:20:35,816] [WARNING] Not Found: /api/spotnumcompared
[2018-10-17 10:20:35,822] [WARNING] "POST /api/spotnumcompared HTTP/1.1" 404 2937
[2018-10-17 10:21:42,311] [INFO] This is an errormsg
[2018-10-17 10:21:42,315] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 10:26:39,396] [INFO] This is an errormsg
[2018-10-17 10:26:39,400] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 10:29:25,366] [INFO] This is an errormsg
[2018-10-17 10:29:25,371] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 10:31:40,190] [INFO] This is an errormsg
[2018-10-17 10:31:40,195] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 10:34:17,283] [INFO] This is an errormsg
[2018-10-17 10:34:17,291] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 10:36:48,007] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 86, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 15, in post_spot_compard
    print(type(search_keys));
UnboundLocalError: local variable 'type' referenced before assignment
[2018-10-17 10:36:48,281] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16934
[2018-10-17 10:39:34,623] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 86, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 15, in post_spot_compard
    print(type(search_keys));
UnboundLocalError: local variable 'type' referenced before assignment
[2018-10-17 10:39:34,910] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16934
[2018-10-17 10:41:04,931] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 86, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 20, in post_spot_compard
    websites =list(body['websites']);
UnboundLocalError: local variable 'list' referenced before assignment
[2018-10-17 10:41:05,235] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16941
[2018-10-17 10:44:02,601] [INFO] "POST /api/spotcompared HTTP/1.1" 200 595
[2018-10-17 10:44:47,007] [INFO] "POST /api/spotcompared HTTP/1.1" 200 595
[2018-10-17 11:16:42,347] [INFO] "POST /api/spotcompared HTTP/1.1" 200 595
[2018-10-17 11:17:32,128] [INFO] "POST /api/spotcompared HTTP/1.1" 200 595
[2018-10-17 11:19:57,056] [INFO] "POST /api/spotcompared HTTP/1.1" 200 595
[2018-10-17 11:21:40,405] [INFO] "POST /api/spotcompared HTTP/1.1" 200 732
[2018-10-17 14:22:54,004] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 92, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 41, in post_spot_compard
    body = json.loads(request.body);
ValueError: Expected object or value
[2018-10-17 14:22:54,195] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16875
[2018-10-17 14:26:05,399] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 92, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 41, in post_spot_compard
    body = json.loads(request.body);
ValueError: Expected object or value
[2018-10-17 14:26:05,601] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16874
[2018-10-17 14:26:44,912] [INFO] This is an errormsg
[2018-10-17 14:26:44,924] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 14:32:37,255] [INFO] "POST /api/spotcompared HTTP/1.1" 200 2492
[2018-10-17 14:33:03,071] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 3419 vs 9
[2018-10-17 14:33:04,522] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18497
[2018-10-17 14:33:18,759] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 3419 vs 9
[2018-10-17 14:33:20,307] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18497
[2018-10-17 14:33:53,128] [INFO] This is an errormsg
[2018-10-17 14:33:53,132] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 14:33:59,925] [INFO] This is an errormsg
[2018-10-17 14:33:59,933] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 14:34:10,803] [INFO] This is an errormsg
[2018-10-17 14:34:10,809] [INFO] "POST /api/spotcompared HTTP/1.1" 200 47
[2018-10-17 14:34:39,253] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 43, in post_spot_compard
    body = json.loads(request.body);
ValueError: Unexpected character found when decoding object value
[2018-10-17 14:34:39,475] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16932
[2018-10-17 14:34:55,926] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 43, in post_spot_compard
    body = json.loads(request.body);
ValueError: Unexpected character found when decoding object value
[2018-10-17 14:34:56,386] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16933
[2018-10-17 14:35:21,109] [INFO] "POST /api/spotcompared HTTP/1.1" 200 2492
[2018-10-17 14:35:28,293] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 3419 vs 9
[2018-10-17 14:35:29,458] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18497
[2018-10-17 14:35:43,571] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 3419 vs 9
[2018-10-17 14:35:44,980] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18497
[2018-10-17 14:36:18,052] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 4136 vs 9
[2018-10-17 14:36:19,208] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18497
[2018-10-17 14:36:27,495] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1247
[2018-10-17 14:40:06,180] [INFO] "POST /api/spotcompared HTTP/1.1" 200 301
[2018-10-17 14:40:17,612] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 4136 vs 9
[2018-10-17 14:40:18,991] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18521
[2018-10-17 14:40:30,277] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 4136 vs 9
[2018-10-17 14:40:31,791] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18521
[2018-10-17 14:40:41,397] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 4136 vs 0
[2018-10-17 14:40:42,904] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18521
[2018-10-17 14:41:56,992] [INFO] "POST /api/spotcompared HTTP/1.1" 200 301
[2018-10-17 14:42:11,858] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 4136 vs 0
[2018-10-17 14:42:13,131] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18521
[2018-10-17 14:43:11,443] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in post_spot_compard
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 73, in <listcomp>
    list = [get_website_data(website,time_search_key,time_list,search_keys) for website in websites];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in get_website_data
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 32, in <listcomp>
    yAxis = [get_region_data(website, region, time_search_key, time_list) for region in search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 18, in get_region_data
    time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 17, in <listcomp>
    (spot_website_comments_data[time_search_key] == time)].iloc[:, 0].size) for time in
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "E:\Anaconda\envs\en1\lib\site-packages\pandas\core\ops.py", line 1120, in _comp_method_OBJECT_ARRAY
    result = libops.vec_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 128, in pandas._libs.ops.vec_compare
ValueError: Arrays were different lengths: 4136 vs 0
[2018-10-17 14:43:12,776] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 18521
[2018-10-17 14:46:46,738] [INFO] "POST /api/spotcompared HTTP/1.1" 200 317
[2018-10-17 14:47:03,137] [INFO] "POST /api/spotcompared HTTP/1.1" 200 709
[2018-10-17 14:48:11,343] [INFO] "POST /api/spotcompared HTTP/1.1" 200 4476
[2018-10-17 14:49:14,961] [ERROR] Internal Server Error: /api/spotcompared
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 94, in post
    return post_spot_compard(request);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotComparedView.py", line 43, in post_spot_compard
    body = json.loads(request.body);
ValueError: Expected object or value
[2018-10-17 14:49:15,131] [ERROR] "POST /api/spotcompared HTTP/1.1" 500 16875
[2018-10-17 14:51:11,358] [INFO] "POST /api/spotcompared HTTP/1.1" 200 18458
[2018-10-17 14:52:07,498] [INFO] "POST /api/spotcompared HTTP/1.1" 200 18458
[2018-10-17 14:52:38,951] [INFO] "POST /api/spotcompared HTTP/1.1" 200 11467
[2018-10-17 14:53:00,406] [INFO] "POST /api/spotcompared HTTP/1.1" 200 7074
[2018-10-17 14:53:12,010] [INFO] "POST /api/spotcompared HTTP/1.1" 200 7074
[2018-10-17 14:53:59,502] [INFO] "POST /api/spotcompared HTTP/1.1" 200 5342
[2018-10-17 14:54:14,346] [INFO] "POST /api/spotcompared HTTP/1.1" 200 3095
[2018-10-17 14:54:24,337] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1622
[2018-10-17 15:28:05,048] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1186
[2018-10-17 15:41:20,913] [WARNING] "POST /api/spotcompared HTTP/1.1" 401 58
[2018-10-17 15:45:03,652] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1186
[2018-10-17 15:52:40,669] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1186
[2018-10-17 16:00:21,772] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1198
[2018-10-17 16:05:20,433] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1198
[2018-10-17 16:11:21,330] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1382
[2018-10-17 16:14:39,261] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1622
[2018-10-17 16:14:53,324] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1778
[2018-10-17 16:15:14,837] [INFO] "POST /api/spotcompared HTTP/1.1" 200 1002
[2018-10-17 16:16:40,494] [WARNING] Not Found: /api/spodetail/1
[2018-10-17 16:16:40,498] [WARNING] "GET /api/spodetail/1 HTTP/1.1" 404 2924
[2018-10-17 16:18:00,567] [INFO] "GET /api/spotdetail/1 HTTP/1.1" 200 401
[2018-10-17 16:18:02,636] [INFO] "GET /api/spotdetail/1 HTTP/1.1" 200 401
[2018-10-17 16:18:18,132] [INFO] "GET /api/spotlist HTTP/1.1" 200 3193
[2018-10-17 16:18:21,980] [INFO] "GET /api/qdhspotlist HTTP/1.1" 200 3677
[2018-10-17 16:18:50,081] [INFO] "GET /api/spotdetail/1 HTTP/1.1" 200 401
[2018-10-17 16:19:15,405] [INFO] "GET /api/spotdetail/2 HTTP/1.1" 200 545
[2018-10-17 16:19:20,373] [INFO] "GET /api/spotdetail/2 HTTP/1.1" 200 545
[2018-10-17 16:19:52,339] [INFO] "GET /api/spotdetail/3 HTTP/1.1" 200 534
[2018-10-17 16:39:58,374] [ERROR] Internal Server Error: /api/spotdetail/2
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 75, in get
    return get_spot_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 39, in get_spot_detail
    (comments_data['search_key'] == spot) & (comments_data['comment_month'] == nowMonth)];
NameError: name 'nowMonth' is not defined
[2018-10-17 16:39:58,845] [ERROR] "GET /api/spotdetail/2 HTTP/1.1" 500 95745
[2018-10-17 16:41:15,860] [ERROR] Internal Server Error: /api/spotdetail/2
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 75, in get
    return get_spot_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 48, in get_spot_detail
    num_axis,score_axis = [get_region_data(region,time_list) for region in spot_search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 48, in <listcomp>
    num_axis,score_axis = [get_region_data(region,time_list) for region in spot_search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 19, in get_region_data
    num_cnts,score_cnts = [get_time_data(spot_comment_data,time) for time in time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 19, in <listcomp>
    num_cnts,score_cnts = [get_time_data(spot_comment_data,time) for time in time_list];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 10, in get_time_data
    return spot_time_comment_data.iloc[:,0].size,get_score(spot_time_comment_data['comment_score'].mean);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\CommonView.py", line 100, in get_score
    return round(score,1);
TypeError: type method doesn't define __round__ method
[2018-10-17 16:41:17,382] [ERROR] "GET /api/spotdetail/2 HTTP/1.1" 500 137379
[2018-10-17 16:43:03,698] [ERROR] Internal Server Error: /api/spotdetail/2
Traceback (most recent call last):
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Anaconda\envs\en1\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 75, in get
    return get_spot_detail(request,id);
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 48, in get_spot_detail
    num_axis,score_axis = [get_region_data(region,time_list) for region in spot_search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 48, in <listcomp>
    num_axis,score_axis = [get_region_data(region,time_list) for region in spot_search_keys];
  File "D:\资料\GitHub\TourCommentApiPro\TourCommentApi\TourCommentApi\Views\SpotDetailView.py", line 19, in get_region_data
    num_cnts,score_cnts = [get_time_data(spot_comment_data,time) for time in time_list];
ValueError: too many values to unpack (expected 2)
[2018-10-17 16:43:05,404] [ERROR] "GET /api/spotdetail/2 HTTP/1.1" 500 113381
[2018-10-17 16:48:49,492] [INFO] "GET /api/spotdetail/2 HTTP/1.1" 200 545
[2018-10-17 16:49:02,310] [INFO] "GET /api/spotdetail/1 HTTP/1.1" 200 401
[2018-10-17 16:49:19,674] [INFO] "GET /api/spotdetail/6 HTTP/1.1" 200 534
